executables:
  chrome:
    command:
      - /usr/bin/google-chrome-stable
      - --new-tab
  firefox:
    command:
      - /usr/bin/firefox
      - --new-tab
      - --url

shortcuts:
  blank:
    supportedExecutables: ["firefox", "chrome"]
    commandTemplate: "about:blank"
  any:
    supportedExecutables: ["firefox", "chrome"]
    commandTemplate: "%s"
  google:
    supportedExecutables: ["firefox", "chrome"]
    commandTemplate: https://www.google.com/search?q=%s
