executables:
  chrome:
    command:
      - /usr/bin/google-chrome-stable
      - --new-tab
  firefox:
    command:
      - /usr/bin/firefox
      - --new-tab
      - --url

shortcuts:
  any:
    template: "%s"
  blank:
    template: "about:blank"
  google:
    template: https://www.google.com/search?q=%s
