executables:
  chrome:
    command:
      - /usr/bin/google-chrome-stable
      - --new-tab
  firefox:
    command:
      - /usr/bin/firefox
      - --new-tab
      - --url

shortcuts:
  gs:
    supportedExecutables: ["firefox", "chrome"]
    commandTemplate: https://www.google.com/search?q=%s
